name: .NET Workflow

on:
  push:
    branches: [ "feature/app-deploy" ]
  pull_request:
    branches: [ "feature/app-deploy" ]
  workflow_dispatch:  


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: CHDIR
      run: |
        pwd
        cd ${{ github.workspace }}/dotnet-app/SampleWebApplication
        pwd
        ls -a
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      #working-directory: dotnet-app
    - name: Build
      run: dotnet build --no-restore
      #working-directory: dotnet-app
    - name: Test
      run: dotnet test --no-build --verbosity normal
      #working-directory: dotnet-app
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifact-file
        path: ./dotnet-app/artifacts/
