name: .NET Build & Deploy

on:
#  push:
#    branches: [ feature/app-deploy ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: dotnet-app

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: dotnet-app

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
      working-directory: dotnet-app

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: dotnet-app/publish

    - name: Run
      run: dotnet run
      working-directory: dotnet-app

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: application
  
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dotnetappgithubactions'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE1 }}
          package: './application'